import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import './globals.css';
import { ProvidersLayout } from '@/layouts/ProvidersLayout';

const vazir = Vazirmatn({
  variable: '--font-vazir',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl' data-theme='light'>
      <body className={`${vazir.variable} font-vazir antialiased`}>
        <ProvidersLayout>{children}</ProvidersLayout>
      </body>
    </html>
  );
}
