import type { Metadata } from 'next';
import './globals.css';
import { ProvidersLayout } from '@/layouts/ProvidersLayout';
import Head from 'next/head';
import localFont from 'next/font/local';

const vazir = localFont({
  src: '../../public/fonts/vazir/Vazirmatn-VariableFont_wght.ttf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Head>
        <link
          rel='stylesheet'
          href='https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined'
        />
      </Head>
      <html lang='fa' dir='rtl' data-theme='light'>
        <body className={`${vazir.className} antialiased`}>
          <ProvidersLayout>{children}</ProvidersLayout>
        </body>
      </html>
    </>
  );
}
